const GameBoard = require("./utils/game");


let player1 = {
  primaryCards: ["Diluc", "Kaeya", "Sucrose"],
  cardDeck: [
    "magic_guide",
    "sacrificial_bow",
    "white_iron_greatsword",
    "travelers_handy_sword",
    "lucky_dog",
    "dawn_winery",
    "paimon",
    "changing_shifts",
    "leave_it_to_me",
    "sweet_madame",
    "magic_guide",
    "sacrificial_bow",
    "white_iron_greatsword",
    "travelers_handy_sword",
    "lucky_dog",
    "dawn_winery",
    "paimon",
    "changing_shifts",
    "leave_it_to_me",
    "sweet_madame",
    "magic_guide",
    "sacrificial_bow",
    "white_iron_greatsword",
    "travelers_handy_sword",
    "lucky_dog",
    "dawn_winery",
    "paimon",
    "changing_shifts",
    "leave_it_to_me",
    "sweet_madame",
  ],
};

let player2 = {
  primaryCards: ["Diluc", "Kaeya", "Ganyu"],
  cardDeck: [
    "magic_guide",
    "sacrificial_bow",
    "white_iron_greatsword",
    "travelers_handy_sword",
    "lucky_dog",
    "dawn_winery",
    "paimon",
    "changing_shifts",
    "leave_it_to_me",
    "sweet_madame",
    "magic_guide",
    "sacrificial_bow",
    "white_iron_greatsword",
    "travelers_handy_sword",
    "lucky_dog",
    "dawn_winery",
    "paimon",
    "changing_shifts",
    "leave_it_to_me",
    "sweet_madame",
    "magic_guide",
    "sacrificial_bow",
    "white_iron_greatsword",
    "travelers_handy_sword",
    "lucky_dog",
    "dawn_winery",
    "paimon",
    "changing_shifts",
    "leave_it_to_me",
    "sweet_madame",
  ],
};

let gameBoard = new GameBoard(player1, player2);
gameBoard.run();
